site_name: WebWatchr Documentation
repo_url: https://github.com/Emrys-Merlin/web_watchr

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            signature_crossrefs: true
            heading_level: 3
