name: Release a new version

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "src/web_watchr/__init__.py"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: |
          echo "::set-output name=version::$(grep -oP '__version__ = "\K[^"]+' src/web_watchr/__init__.py)"
        shell: bash

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build and publish
        run: |
          make setup-ci
          make build
          make publish
        shell: bash
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PASSWORD }}

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name: v${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
